### ISSUE TITLE
Milestone v1

### ISSUE THREAD

**Issue by xNaCly** [xNaCly/Surveys-M-und-S#1]
# Survey builder:
- [x] insert the current date and the test/survey number into the corresponding input fields
- [x] take input from all not disabled inputfields and insert them into the `submitObject`
- [x] allow the user to create and add several simple different input types:
  ```
  textinput
  emailinput
  dateinput
  ```
- [x] allow the user to create and add more sophisticated input types
  ```
  selectinput
  radioinput
  ```

- [x] insert all dynamicly created properties into the `submitObject`
- [x] fix the weird styling of the property generator
- [x] add a button to remove all properties
- [x] implement the above not only for survey taker properties but for questions in the survey
- [x] insert all dynamicly created questions into the `submitObject`
